name: CD

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

env:
  CODECOV_CLI_UPSTREAM: "https://cli.codecov.io/latest/alpine/codecov"

jobs:
  codecov-upload:
    runs-on: docker
    container: node:25-alpine
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    continue-on-error: true
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: tarpaulin

      - run: |
          apk add --no-cache curl gnupg

          curl -O ${CODECOV_CLI_UPSTREAM}

          curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
          gpg --keyring trustedkeys.gpg --list-keys

          curl -O ${CODECOV_CLI_UPSTREAM}.SHA256SUM
          curl -O ${CODECOV_CLI_UPSTREAM}.SHA256SUM.sig
          gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM

          sha256sum -c codecov.SHA256SUM
          chmod +x codecov
          ./codecov --version

          ./codecov -v upload-process --dir tarpaulin --git-service forgejo -t ${{ secrets.CODECOV_TOKEN }}

