name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  SPHINX_DEFAULT_DOC_VERSION: "master"
  TYPOS_UPSTREAM: "https://github.com/crate-ci/typos/releases/download/v1.44.0/typos-v1.44.0-x86_64-unknown-linux-musl.tar.gz"
  CODECOV_CLI_UPSTREAM: "https://cli.codecov.io/latest/alpine/codecov"

jobs:
  sync-mirrors:
    runs-on: docker
    container: node:25-alpine
    if: forgejo.ref_name == 'master'
    continue-on-error: true

    steps:
      - name: Install utilities
        run: apk add --no-cache git openssh

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/privatekey
          echo "${{ secrets.GIT_ACCESS_KEY }}" >> ~/.ssh/privatekey
          echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/privatekey
          chmod 600 ~/.ssh/privatekey

      - name: Add known hosts
        run: |
          ssh-keyscan git.maxrdz.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push to mirrors
        run: |
          git clone --mirror ${{ github.server_url }}/${{ github.repository }} repo.git
          cd repo.git
          ssh-agent sh -c 'ssh-add ~/.ssh/privatekey; git push -v --mirror git@github.com:donet-server/donet'
          ssh-agent sh -c 'ssh-add ~/.ssh/privatekey; git push --all git@gitlab.com:donet-server/donet'

  commit-validation:
    runs-on: docker
    container: node:25-alpine
    needs: sync-mirrors
    steps:
      - name: actions/checkout@v6
        uses: https://git.maxrdz.com/actions/checkout@v6

      - name: Install Python3
        run: apk add --no-cache python3 py3-pip git

      - name: Validate Commit
        run: python build-aux/validate-commit.py "${{ github.event.head_commit.message || github.event.commits[0].message }}"

  typos:
    runs-on: docker
    container: node:25-alpine
    needs: sync-mirrors
    steps:
      - name: actions/checkout@v6
        uses: https://git.maxrdz.com/actions/checkout@v6

      - name: Install Typos binary
        run: |
          apk add --no-cache wget tar
          wget ${TYPOS_UPSTREAM}
          mkdir .tmp
          tar -xzf typos-v*.tar.gz -C .tmp/

      - name: Run Typos
        run: ./.tmp/typos

  cargo-fmt:
    runs-on: docker
    container: maxrdz1/forgejo-ci:3.8.26
    needs: sync-mirrors
    steps:
      - name: actions/checkout@v6
        uses: https://git.maxrdz.com/actions/checkout@v6

      - name: Run rustfmt
        run: |
          echo "" >> donet-daemon/src/meson.rs
          rustc -Vv && cargo -Vv
          cargo fmt --version
          cargo fmt --all -- --color=always --check

  build:
    runs-on: docker
    container: maxrdz1/forgejo-ci:3.8.26
    needs: [cargo-fmt, typos]
    steps:
      - name: actions/checkout@v6
        uses: https://git.maxrdz.com/actions/checkout@v6

      - name: Get Meson version
        id: meson-version
        run: |
          echo "Meson version is $(meson --version)"
          echo "MESON_VERSION=$(meson --version)" >> $FORGEJO_ENV

      - name: Restore Meson build cache
        uses: https://git.maxrdz.com/actions/cache/restore@v5
        with:
          path: build
          key: meson-${{ env.MESON_VERSION }}-cache-build-${{ forgejo.ref_name }}

      - name: Meson build
        run: |
          if [ ! -d build ]; then
            meson setup build -Dprofile=debug
          fi
          meson compile -C build

      - name: Run linting
        run: meson compile linting -C build

      - name: Run unit tests
        run: meson compile tests -C build

      - name: Run cargo-deny
        run: meson compile deny -C build

      - name: Run cargo-tarpaulin
        run: |
          meson compile code-coverage -C build

          mkdir tarpaulin
          echo "Copying code coverage output files into artifact directory..."
          cp -r build/target/tarpaulin tarpaulin
          chmod -R a=rwx tarpaulin

      - name: actions/upload-artifact@v3
        uses: https://git.maxrdz.com/actions/upload-artifact@v3
        with:
          name: code-coverage
          path: tarpaulin
          retention-days: 7

      - name: Run cargo-doc
        run: |
          meson compile cargo-doc -C build

          mkdir doc
          echo "Copying cargo-doc build into artifact directory..."
          cp -r build/target/doc/* doc
          chmod -R a=rwx doc

      - name: actions/upload-artifact@v3
        uses: https://git.maxrdz.com/actions/upload-artifact@v3
        with:
          name: rust-documentation
          path: doc
          retention-days: 7

      - name: Save Meson build cache
        uses: https://git.maxrdz.com/actions/cache/save@v5
        with:
          path: build
          key: meson-${{ env.MESON_VERSION }}-cache-build-${{ forgejo.ref_name }}

  documentation:
    runs-on: docker
    container: maxrdz1/forgejo-ci:3.8.26
    needs: build
    steps:
      - name: actions/checkout@v6
        uses: https://git.maxrdz.com/actions/checkout@v6

      - name: Get Meson version
        id: meson-version
        run: |
          echo "Meson version is $(meson --version)"
          echo "MESON_VERSION=$(meson --version)" >> $FORGEJO_ENV

      - name: Restore Meson build cache
        uses: https://git.maxrdz.com/actions/cache/restore@v5
        with:
          path: build
          key: meson-${{ env.MESON_VERSION }}-cache-doc-${{ forgejo.ref_name }}

      - name: Get Python version
        id: python-version
        run: |
          echo "$(python3 --version)"
          echo "PYTHON_VERSION=$(python3 --version | grep -Eo '.\..*\..*$')" >> $FORGEJO_ENV

      - name: Restore Python venv cache
        uses: https://git.maxrdz.com/actions/cache/restore@v5
        with:
          path: venv
          key: venv-${{ env.PYTHON_VERSION }}-cache-doc-${{ forgejo.ref_name }}

      - name: Setup Python venv
        run: |
          if [ ! -d venv ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          source venv/bin/activate

          if [ ! -d build ]; then
            meson setup build -Dprofile=debug -Dci_branch=${{ forgejo.ref_name }}
          fi
          meson compile sphinx -C build

          mkdir doc
          echo "Copying Sphinx build into artifact directory..."
          cp -r build/sphinx/* doc
          chmod -R a=rwx doc

      - name: Save Meson build cache
        uses: https://git.maxrdz.com/actions/cache/save@v5
        with:
          path: build
          key: meson-${{ env.MESON_VERSION }}-cache-doc-${{ forgejo.ref_name }}

      - name: Save Python venv cache
        uses: https://git.maxrdz.com/actions/cache/save@v5
        with:
          path: venv
          key: venv-${{ env.PYTHON_VERSION }}-cache-doc-${{ forgejo.ref_name }}

      - name: actions/upload-artifact@v3
        uses: https://git.maxrdz.com/actions/upload-artifact@v3
        with:
          name: sphinx-documentation
          path: doc
          retention-days: 7

  codecov-upload:
    runs-on: docker
    container: node:25-alpine
    needs: build
    if: forgejo.ref_name == 'master'
    continue-on-error: true
    steps:
      - name: actions/download-artifact@v3
        uses: https://git.maxrdz.com/actions/download-artifact@v3
        with:
          name: code-coverage
          path: tarpaulin

      - name: Install GPG
        run: apk add --no-cache curl gnupg

      - name: Download Codecov binary
        run: curl -O ${CODECOV_CLI_UPSTREAM}

      - name: Verify download
        run: |
          curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
          gpg --keyring trustedkeys.gpg --list-keys

          curl -O ${CODECOV_CLI_UPSTREAM}.SHA256SUM
          curl -O ${CODECOV_CLI_UPSTREAM}.SHA256SUM.sig
          gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM

          sha256sum -c codecov.SHA256SUM
          chmod +x codecov
          ./codecov --version

      - name: Upload coverage files
        run: ./codecov -v upload-process --dir tarpaulin --git-service gitlab -t ${{ secrets.CODECOV_TOKEN }}
