name: Continuous Integration

on:
  push:
  pull_request:

env:
  SPHINX_DEFAULT_DOC_VERSION: "master"
  TYPOS_UPSTREAM: "https://github.com/crate-ci/typos/releases/download/v1.22.7/typos-v1.22.7-x86_64-unknown-linux-musl.tar.gz"

jobs:
  commit-validation:
    runs-on: docker
    container: python:3.12-alpine
    steps:
      - uses: actions/checkout@v4
      - run: python build-aux/validate-commit.py "${{ github.event.head_commit.message }}"

  typos:
    runs-on: docker
    container: alpine
    steps:
      - uses: actions/checkout@v4
      - run: |
          apk add --no-cache wget tar
          wget ${TYPOS_UPSTREAM}
          mkdir .tmp
          tar -xzf typos-v*.tar.gz -C .tmp/
          ./.tmp/typos

  cargo-fmt:
    runs-on: docker
    container: rust:slim
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup component add rustfmt
          echo "" >> donet-daemon/src/meson.rs
          rustc -Vv && cargo -Vv
          cargo fmt --version
          cargo fmt --all -- --color=always --check

  cargo-deny:
    runs-on: docker
    container: ubuntu:latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Cache Meson
        uses: actions/cache@v4
        with:
          path: build
          key: meson-cache-deny-${{ github.ref_name }}

      - run: |
          apt-get update
          apt-get install -y git meson rustup pkg-config python3 python3-venv
          apt-get install -y libssl-dev openssl
          rustup default stable
          rustup component add clippy rustfmt
          meson setup build -Dprofile=debug
          meson compile deny -C build

  build:
    runs-on: docker
    container: ubuntu:latest
    needs: [cargo-fmt, typos]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Meson
        uses: actions/cache@v4
        with:
          path: build
          key: meson-cache-build-${{ github.ref_name }}

      - run: |
          apt-get update
          apt-get install -y git meson rustup pkg-config python3 python3-venv
          apt-get install -y libssl-dev openssl
          rustup default stable
          rustup component add clippy rustfmt

          meson setup build -Dprofile=debug
          meson compile -C build
          meson compile linting -C build

  testing:
    runs-on: docker
    container: ubuntu:latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - run: |
          apt-get update
          apt-get install -y git meson rustup pkg-config python3 python3-venv
          apt-get install -y libssl-dev openssl
          rustup default stable

          meson setup build -Dprofile=debug
          meson compile tests -C build

      - uses: actions/upload-artifact@v4
        with:
          name: test-build
          path: build
          retention-days: 7

  documentation:
    runs-on: docker
    container: ubuntu:latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Cache Meson
        uses: actions/cache@v4
        with:
          path: build
          key: meson-cache-doc-${{ github.ref_name }}

      - run: |
          apt-get update
          apt-get install -y git meson rustup pkg-config python3 python3-venv
          apt-get install -y libssl-dev openssl

          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r docs/requirements.txt

          meson setup build -Dprofile=debug -Dci_branch=${{ github.ref_name }}
          meson compile sphinx -C build
          meson compile cargo-doc -C build

          mkdir doc
          cp -r build/sphinx/* doc
          cp -r build/target/doc/* doc
          chmod -R a=rwx doc

      - uses: actions/upload-artifact@v4
        with:
          name: project-documentation
          path: doc
          retention-days: 7

  cargo-tarpaulin:
    runs-on: docker
    container: ubuntu:latest
    needs: testing
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: test-build
          path: build

      - run: |
          apt-get update
          apt-get install -y git meson rustup pkg-config python3 python3-venv
          apt-get install -y libssl-dev openssl
          rustup default stable

          meson compile code-coverage -C build

          mkdir tarpaulin
          chmod -R a=rwx tarpaulin
          cp -r build/target/tarpaulin tarpaulin

      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: tarpaulin
          retention-days: 7

