name: Sync

on:
  push:
    branches: [ "master" ]

jobs:
  sync-mirror:
    runs-on: docker
    container: node:25-alpine
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    continue-on-error: true

    steps:
      - name: Install utilities
        run: apk add --no-cache git openssh

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_ACCESS_KEY }}" > ~/.ssh/privatekey
          chmod 600 ~/.ssh/privatekey

      - name: Add known hosts
        run: |
          ssh-keyscan git.maxrdz.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror repository
        run: |
          git clone --mirror ${{ github.server_url }}/${{ github.repository }} repo.git
          cd repo.git
          ssh-agent sh -c 'ssh-add ~/.ssh/privatekey; git push -v --mirror git@github.com:donet-server/donet'
